### ISSUE TITLE
关于网卡接口的疑问？

### ISSUE THREAD

**Issue by ismethr** [wenyushu/MaxSun_TERMINATOR_B760M_D5#2]
“**此主板自带网卡接口协议为 CNVi，此协议在 macOS 中无法驱动**” 针对这个，我这个是 D4 Wi-Fi 自带 AX101 网卡的版本，看了说明（D5 版本没写）这个网卡接口是支持 PCIE CNVi USB 协议的，自带的 AX101 网卡是可以使用 **itlwm** 驱动的。不知道你的 D5 版本的怎么样，如果也是一样的应该也是可以驱动的，如果确实是 CNVi 那就没办法了。

**Comment by wenyushu** [comment]
D5 版本预留的网卡接口仅支持 CNVi 协议，D4 的没测试过（不过看 PCIe 布线的话，应该是还支持额外的协议），不过具体得看主板上有没有写 "Only CNVi"

**Comment by ismethr** [comment]
ok 那就可以确定 D5 版本 Only CNVi，D4 Wi-Fi 可以确定是都支持的。
